name: model
on:
  push:
    paths: # Run only when files under neuralprophet/ are modified
      - neuralprophet/**
    branches: # Run only on these branches
      - main
      - develop
  pull_request: # Run on pull requests
    branches:
      - main
      - develop
  workflow_dispatch:
jobs:
  metrics:
    runs-on: ubuntu-latest
    container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Download metrics from main
        uses: dawidd6/action-download-artifact@v2
        with:
          repo: ourownstory/neural_prophet
          branch: main
          name: metrics
          path: tests/metrics-main/
          if_no_artifact_found: warn
      - name: Compare performance
        run: |
          echo "## Model Benchmark" >> report.md
      - name: Publish report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "<details>\n<summary>Model training plots</summary>\n" >> report.md
          echo "## Model Training" >> report.md
          echo "### PeytonManning" >> report.md
          echo "### YosemiteTemps" >> report.md
          echo "### AirPassengers" >> report.md
          echo "\n</details>" >> report.md
          # Post reports as comments in GitHub PRs
          cml comment update --target=pr report.md # post to PR
          # cml check create --title=ModelReport report.md # update status of check in PR
      - name: Upload metrics if on main
        uses: actions/upload-artifact@v3
        with:
          name: metrics
          path: tests/metrics/
