name: model
on:
  push:
    paths: # Run only when files under neuralprophet/ are modified
      - neuralprophet/**
    branches: # Run only on these branches
      - main
      - develop
  pull_request: # Run on pull requests
    branches:
      - main
      - develop
  workflow_dispatch:
jobs:
  metrics:
    runs-on: ubuntu-latest
    container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Compare performance
       run: |
         echo "## Model Benchmark" >> report.md
         python tests/metrics/compareMetrics.py >> report.md
      - name: Publish report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "<details>\n<summary>Model training plots</summary>\n" >> report.md
          echo "## Model Training" >> report.md
          echo "### PeytonManning" >> report.md
          echo "### YosemiteTemps" >> report.md
          echo "### AirPassengers" >> report.md
          echo "\n</details>" >> report.md
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY_OWNER
          echo ${{ github.event.pull_request.head.repo.html_url }}
          cml comment update --target pr/${{github.event.issue.number}} --repo=${{ github.event.pull_request.head.repo.html_url }} report.md # post to PR
          cml check create --title=ModelReport report.md # update status of check in PR
      - name: Upload metrics if on main
        uses: actions/upload-artifact@v3
        with:
          name: metrics
          path: tests/metrics/
